# Configuration for object detection node
/leftTB:
  ros__parameters:
    # print debug output
    debug: true
    # rotate images? 0/90/180/270
    rotation: 90
    # image source topic
    in_topic: "/camera_left/frameset"
    # image destination topic
    out_topic: "/background/color"
    out_full_topic: "/background/color_full"
    out_small_topic: "/background/color_small"
    out_depth_topic: "/background/depth"
    fps_topic: "/background/fps"
    max_fps: 30.0
    print_fps: true
    FPS_STR: "FPS"
    # Use sensor data Quality of Service for messages
    qos_sensor_data: true
    # Message queue size
    qos_history_depth: 5
    # threshold for cutting background
    depth_thr: 1800

